# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c97d47c9ded0356f815373c6e50edb9192bdbb9cf602c77b972c9d08c4abd3e456d8ac8dd448e3946b9b72a80c1fd0df2d130d0e279b3834888610ce1563e68

test:
  secret_key_base: 41068cd4c1329d1d8ce94db7bb58e3e4e189f7f85fe5074f00179c932a611e1011326abcbf42df4e75a9c34d2c111b7ed5e70fcb8f449ba5282b329278fe165f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
